# .goreleaser.yaml
before:
  hooks:
    - go mod tidy

builds:
  - id: anc
    binary: anc
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: add-n-commit
    repository:
      owner: oconnorjohnson
      name: homebrew-tap
    homepage: "https://github.com/oconnorjohnson/add-n-commit"
    description: "AI-powered Git commit message generator"
    license: "MIT"
    install: |
      bin.install "anc"
    test: |
      system "#{bin}/anc", "--version"
